<?php

return [
    /*
    |--------------------------------------------------------------------------
    | Admin Language Lines
    |--------------------------------------------------------------------------
    */
	'user_groups' 		 => 'User Groups',
    'group_name'         => 'Group Name',
    'created_at'         => 'Created At',
    'updated_at'         => 'Updated At',
    'action'             => 'Action',
    'approved'           => 'Đã duyệt',
    'add_new_group'      => 'Add Group',
    'search'             => '<i class="fa fa-search" aria-hidden="true"></i>',
    'search-placeholder' => 'key word...',
    'manager'            => 'Manager',
    'chooseRoom'         => 'Choose Room',
    'chooseUser'         => 'Choose User',
    'chooseAbsentreason' => 'Choose Absence Reason',
    'add_new_absence'    => 'Add Absence',
    'timekeepings'       => 'Timekeeping',
    'active'             => 'Active',
    'room'               => 'Room',
    'stt'                => '#',
    'sum'                => 'Sum',
    'absences'           => 'Absences',
    'list-document'      => 'Document List',
    'note'               => 'Note',
    'status'             => 'Status',
    'name'               => 'Full Name',
    'tel'                => 'Telephone',
    'email'              => 'Email',
    'export-excel'       => 'Export Excel',
    'add-absence'        => 'Add Absence',
    'rooms'              => 'Danh sách phòng',
    'staff'              => 'Staff',
    'Staffs_name'        => 'Staff Name',
    'request_manager'    => 'Request Manager',
    'btnCancel'          => 'Cancel',
    'btnSave'            => 'Save',
    'btnDelete'          => 'Delete',
    'btnAddReg'          => 'Add',
    'role_power'         => 'Role',
    'btnUpdateReg'       => 'Update',
    'startDate'          => 'Start Date',
    'endDate'            => 'End Date',
    'startTime'          => 'Start Time',
    'endTime'            => 'End Time',
    'btnSearch'          => '<i class="fa fa-search" aria-hidden="true"></i>',
    'day'                => 'Day',
    'on'                 => 'On',
    'off'                => 'Off',
    'times'              => 'Times',
    'working-day'        => 'Working Day',
    'contents'           => 'Contents',
    'approved'           => 'Approved',
    'not_approved'       => 'Not Approved',
    'Export_QR'          => 'Export QR',
    'Export_PDF'         => 'Export PDF',
    'import'             => 'Import',
    'Active_status'      => 'Trạng thái hoạt động',
    'Add_history'        => 'Thêm lịch sử',
    'view'               => 'Xem',
    'nullData'           => 'Không có dữ liệu',
    'Unfinished'         => 'Chưa hoàn thành',
    'Finish'             => 'Hoàn thành',
    'PheDuyet'           => 'Phê duyệt',
    'all_status'         => 'Tất cả trạng thái',

    'daily' => [
        'daily_report'   => 'Báo cáo',
        'Date'           => 'Ngày làm',
        'Project'        => 'Dự án',
        'Screen_Name'    => 'Màn hình',
        'Type_Of_Work'   => 'Kiểu công việc',
        'Working_Time'   => 'Thời gian',
        'progressing'    => 'Tiến độ(%)',
        'Progressing'    => '%',
        'Delay'          => 'Giờ trễ(h)',
        'Note'           => 'Ghi chú',
        'Status'           => 'Trạng thái',
        'Date_Create'    => 'Ngày tạo',
        'add_daily'      => 'Thêm báo cáo',
        'add_daily_one'  => 'Thêm báo cáo',
        'chooseProject'  => 'Chọn dự án',
        'chooseWorkType' => 'Kiểu công việc',
        'time_working'   => 'Thời gian làm',
        'show_daily_report'   => 'Hiện tổng hợp báo cáo',
        'choose_year'   =>  'Chọn năm',

    ],

    'user' => [
        'full_name'                 => 'Họ và Tên',
        'profile_image'             => 'Ảnh',
        'phone_number'              => 'Số điện thoại',
        'phone_number_short'        => 'SĐT',
        'birthday'                  => 'Ngày sinh',
        'add_new_user'              => 'Thêm thành viên',
        'username'                  => 'Tên đăng nhập',
        'password'                  => 'Mật khẩu',
        'password_confirmation'     => 'Xác nhận mật khẩu',
        'gender'                    => 'Giới tính',
        'marital_status'            => 'Hôn nhân',
        'telephone'                 => 'Điện thoại',
        'email'                     => 'Email',
        'location'                  => 'Quê quán',
        'current_address'           => 'Chỗ ở hiện tại',
        'relative_person'           => 'Người thân',
        'relationship'              => 'Quan hệ với nhân viên',
        'relative_person_telephone' => 'Điện thoại người thân',
        'male'                      => 'Nam',
        'female'                    => 'Nữ',
        'single'                    => 'Độc thân',
        'married'                   => 'Đã kết hôn',
        'please_select'             => 'Vui lòng chọn',
        'group'                     => 'Nhóm nhân viên',
        'IDFM'                      => 'Mã máy chấm công',
        'room'                      => 'Phòng làm việc',
        'department'                => 'Chức vụ',
        'work_time'                 => 'Giờ làm việc',
        'join_date'                 => 'Ngày vào',
        'official_date'             => 'Ngày làm chính thức',
        'official_date_short'       => 'Chính thức',
        'out_date'                  => 'Ngày nghỉ việc',
        'note'                      => 'Ghi chú',
        'status'                    => 'Trạng thái',
        'active'                    => 'Hoạt động',
        'deactive'                  => 'Không hoạt động',
        'age'                       => 'Tuổi',
        'users_management'          => 'Danh sách nhân viên',
        'prog_skill'                => 'Ngôn ngữ lập trình',
        'db_skill'                  => 'Cơ sở dữ liệu',
        'year_exp'                  => 'Số năm kinh nghiệm',
        'ID'                        => 'STT',
        'idfm'                      => 'IDFM',
        'avatar'                    => 'Ảnh',
        'end_time_of_day'           => 'Giờ kết thúc',
        'all_col'                   =>  'All Field',
        'expiration_date'           => 'Ngày hết hạn',
        'workAt'                    => 'Làm việc tại',
        'deWorkAt'                  => 'Tại nhà',
        'AcWorkAt'                  => 'Tại công ty',
    ],

    'user-detail'  => [
        'infoUser'                  => 'Thông tin cá nhân',
        'role'                      => 'Phân quyền',
        'changePassword'            => 'Đổi mật khẩu',
        'newPassword'               => 'Mật khẩu mới',
        'confirmPassword'           => 'Nhập lại mật khẩu',
        'current_password'          => 'Mật khẩu hiện tại',

    ],

    'room' => [
        'rooms_management' => 'Phòng ban',
        'name'             => 'Tên phòng',
        'add_new_room'     => 'Thêm phòng mới',
        'status'           => 'Trạng thái',
        'meeting_room'     => 'Phòng họp',
        'active'           => 'Trạng thái',
    ],

    'work-detail'  => [
        'Add_a_description_of_this_tag'         => 'Thêm mô tả về thẻ này',
        'To_do_list'                            => 'Danh sách việc cần làm',
        'To_do'                                 => 'Việc cần làm',
        'Expiration_date'                       => 'Ngày hết hạn',
    ],

    'timekeeping' => [
        'userId'             => 'Mã nhân viên',
        'work'               => 'Công làm',
        'solantre'           => 'Số lần trễ',
        'sogiotre'           => 'Số giờ trễ',
        'solansom'           => 'Số lần sớm',
        'sogiosom'           => 'Số giờ sớm',
        'overtime'           => 'Tăng ca',
        'absence'            => 'Vắng',
        'pheps'              => 'Phép (P)',
        'holiday'            => 'Ngày lễ',
        'absenceHaveMoney'   => 'Nghỉ có lương (H100)',
        'absenceNotMoney'    => 'Không lương (Ro)',
        'TGvaora'            => 'TG Vào ra',
        'late'               => 'Trễ',
        'soon'               => 'Sớm',
        'total_work'         => 'Công',
        'T_Gio'              => 'T.Giờ',
        'DL_month'           => 'Tháng',
        'add_timekeeping'    => 'Thêm chấm công',
    ],

    'meeting' => [
        'meeting_users'       => 'Thành phần tham gia',
        'meeting_room'        => 'Phòng họp',
        'please_select'       => 'Vui lòng chọn',
        'search'              => '<i class="fa fa-search" aria-hidden="true"></i>',
        'purpose'             => 'Mục đích cuộc họp',
        'content'             => 'Nội dung chính của cuộc họp',
        'day_meeting'         => 'Ngày họp',
        'time_start_meeting'  => 'Thời gian bắt đầu họp',
        'time_end_meeting'    => 'Thời gian kết thúc họp',
        'total_time_meeting'  => 'Thời gian họp',
        'meeting_users_2'     => 'NV tham gia',
        'meeting_host'        => 'Người chủ trì',
        'employer'            => 'Nhân viên',
        'action'              => 'Hành động',
        'register'            => 'Người tạo',
        'host'                => 'Người chủ trì',
        'number_of_employers' => 'Số người tham gia',
        'hour_meeting'        => 'Giờ họp',
        'add_new_meeting'     => 'Thêm ca họp',
    ],

    'project' => [
        'projects_management' => 'Quản lý dự án',
        'add_new_project'     => 'Thêm dự án',
        'name'                => 'Tên dự án',
        'customer'            => 'Khách hàng',
        'start_date'          => 'Ngày bắt đầu',
        'end_date'            => 'Ngày kết thúc',
        'name_short'          => 'Tên viết tắt',
        'describe_project'    => 'Mô tả dự án',
        'Leader'              => 'Trưởng nhóm',
        'Member'              => 'Thành viên',
    ],

    'overtime' => [
        'management'      => 'Danh sách chi tiết giờ làm thêm',
        'add_new'         => 'Thêm mới',
        'break_time'      => 'Thời gian nghỉ',
        'week_day'        => 'Thứ',
        'stime'           => 'Thời gian bắt đầu',
        'etime'           => 'Thời gian kết thúc',
        'work_hours'      => 'Số giờ làm',
        'project_name'    => 'Tên dự án',
        'content'         => 'Nội dung',
        'created_date'    => 'Ngày tạo',
        'approved_date'   => 'Ngày duyệt',
        'approved_person' => 'Người duyệt',
        'status'          => 'Trạng thái',
        'employer'        => 'Nhân viên',
        'project'         => 'Dự án',
        'request_manager' => 'Người quản lý',
        'overtime_days'   => 'Tổng số lần xin làm thêm',
        'overtime_hours'  => 'Tổng số giờ làm thêm',
        'action'          => 'Hành động',
        'view'            => 'Xem',
        'reject_reason'   => 'Lý do từ chối',
        'report'          => 'Tổng hợp báo cáo',
        'total'           => 'Tổng',
        'percent'         => '%',
        'fullname'        => 'Họ và tên',
        'list_overtime'   => 'Danh sách tổng quan',
        'list_approve'    => 'Danh sách chờ duyệt giờ làm thêm',
        'time_work'       => 'Thời gian',
    ],

    'skill' => [
        'profile'    => 'Hồ sơ năng lực',
        'management' => 'Quản lý hồ sơ năng lực'
    ],

    'masterdata' => [
        'management'         => 'Quản lý Master Data',
        'add'                => 'Thêm',
        'name'               => 'Tên văn bản',
        'type_name'          => 'kiểu văn bản',
        'data_value'         => 'Mã văn bản',
        'data_display_order' => 'Order',
        'description'        => 'Mô tả',
        'key'                => 'DataKey'
    ],

    'event' => [
        'management'        => 'Quản lý sự kiện',
        'name'              => 'Tên sự kiện',
        'start_date'        => 'Ngày bắt đầu',
        'end_date'          => 'Ngày kết thúc',
        'created_date'      => 'Ngày tạo',
        'created_by'        => 'Người tạo',
        'action'            => 'Hành động',
        'add'               => 'Thêm sự kiện',
        'select_type'       => 'Chọn loại thiết bị',
        'anser'             => 'Trả lời',
        'ansers'            => 'Câu trả lời',
        'add_ansers'        => 'Thêm câu trả lời',
        'vote'              => 'Vote',
        'type-event'        => 'Loại sự kiên',
        'day-off'           => 'Ngày nghỉ',
        'day-lambu'         => 'Ngày nghỉ',
        'day-off-KBS'       => 'Ngày nghỉ KBS',
        'other-event'       => 'Sự kiện khác',
        'event-content'     => 'Nội dung sự kiện',
        'select_the_answer' => 'Hãy chọn câu trả lời',
        'General_diagram'   => 'Sơ đồ tổng hợp',
    ],

    'vote' => [
        'General_diagram'       => 'Sơ đồ tổng hợp',
        'Detailed_results'      => 'Kết quả chi tiết',
    ],
    'answer-detail' => [
        'question-content'      => 'Nội dung câu hỏi',
    ],

    'question-detail' => [
        'Kind_of_question'      => 'Loại câu hỏi',
        'Related_questions'     => 'Câu hỏi liên quan',
    ],

    'equipment' => [
        'management'            => 'Danh sách thiết bị',
        'add'                   => 'Thêm thiết bị',
        'add_store'             => 'Nhập kho',
        'add_type'              => 'Thêm loại thiết bị',
        'type'                  => 'Loại thiết bị',
        'quantity'              => 'Số lượng',
        'status'                => 'Tình trạng',
        'name'                  => 'Tên thiết bị',
        'serial_number'         => 'Serial Number',
        'buy_date'              => 'Ngày mua',
        'period_date'           => 'Thời hạn bảo hành',
        'warranty'              => 'Còn bảo hành',
        'warranty_expired'      => 'Hết bảo hành',
        'provider'              => 'Nhà cung cấp',
        'unit_price'            => 'Giá',
        'user_owner'            => 'Người dùng',
        'info'                  => 'Thông số kỹ thuật',
        'note'                  => 'Ghi chú',
        'register_room_id'      => 'Phòng ban người dùng',
       	// 'register_id'           => 'Người dùng',
        'deal_date'             => 'Ngày bàn giao',
        'Handover_user'         => 'Người bàn giao',
        'The_handover_user'     => 'Người nhận bàn giao',
        'Updated_person'        => 'Người cập nhật',
        'room_id'               => 'Vị trí đặt thiết bị',
        'type_id'               => 'Mã loại thiết bị',
        'type_name'             => 'Tên loại thiết bị',
        'created_user'          => 'Người tạo',
        'created_at'            => 'Ngày tạo',
        'updated_at'            => 'Ngày cập nhật',
        'select_register_room'  => 'Phòng ban người dùng',
        'select_register'       => 'Người dùng',
        'select_type'           => 'Loại thiết bị',
        'select_status'         => 'Trạng thái thiết bị',
        'status'                => 'Trạng thái',
        'code'                  => 'Mã thiết bị',
        'handover'              => 'Luân chuyển thiết bị',
        'receive_owner'         => 'Bên nhận',
        'old_owner'             => 'Bên bàn giao',
        'current_status'        => 'Tình trạng hiện tại',
        'old_status'            => 'Tình trạng cũ',
        'list'                  => 'Các thiết bị',
        'registration'          => 'Đăng ký thay đổi thiết bị',
        'Change_device'         => 'Đổi thiết bị',
        'DeviceChange'          => 'Thiết bị đổi',
        'New_equipment'          => 'Thiết bị mới',
        'type_list'             => 'Các loại thiết bị',
        'status_list'           => 'Các tình trạng',
        'register_code'         => 'Mã đơn',
        'register_user'         => 'Người đăng ký',
        'requests'              => 'Số lượng yêu cầu',
        'processing_requests'   => 'Đang xử lý',
        'processed_requests'    => 'Đã hoàn thành',
        'rejected_requests'     => 'Từ chối',
        'form_status'           => 'Tình trạng đơn',
        'add_registration_form' => 'Tạo đơn đăng ký',
        'store'                 => 'Kho',
        'Kind_of_change'        => 'Loại thay đổi',
        'The_changes'           => '[Các thay đổi]',
        'Request'               => 'Yêu cầu',
        'Approved'              => 'Đã duyệt',
        'Petitioner'            => 'Người yêu cầu',
        'approved_Petitioner'   => 'Đã duyệt / Yêu cầu',
        'Source_equipment'      => 'Nguồn thiết bị',
        'device'                => 'Thiết bị',
        'Device_status'         => 'Tình trạng thiết bị',
        'Source'                => 'Nguồn',
        'Users'                 => 'Người sử dụng',
        'Date_of_delivery'      => 'Ngày bàn giao',
        'Create_votes'          => 'Tạo phiếu',
        'Code'                  => 'Mã hiệu',
        'listThietBi'           => 'Danh sách thiết bị được chọn',
        'Warranty_date'         => 'Ngày bảo hành',
        'List_of_equipment_handed'           => 'Danh sách thiết bị bàn giao',
        'Content_corrected'                  => 'Nội dung sửa chữa',
        'Fix_maintenance_schedule'           => 'Sửa lịch bảo trì',
        'Office'                => 'Văn phòng',
        'update_add'            => 'Cập nhật thiết bị',
        'copy_add'              => 'Sao chép thiết bị',
        'update_type'           => 'Cập nhật loại thiết bị',
        'update_registration_form'           => 'Sửa đơn đăng ký',
        'Approved_title_detail'              => 'Duyệt đổi thiết bị',
        'Approved_title_add_detail'          => 'Duyệt thêm thiết bị',
        'Approved_note'         => 'Lý do thay đổi',
        'Maintenance_title'     => 'Bảo hành bảo trì',
        'Approved_choose'       => 'Duyệt',
        'Approved_rejected_requests'         => 'Đã từ chối',
        'Qr_code'               => 'Qr code',
    ],

    'absence' => [
        'absence'              => 'Danh sách vắng mặt',
        'absence_list_approve' => 'Danh sách chờ duyệt',
        'absentreason'         => 'Hình thức vắng mặt',
        'absence-management'   => 'Quản lý vắng mặt',
        'absence-reports'      => 'Báo cáo tổng hợp vắng mặt',
        'chooseManagement'     => 'Chọn quản lý',
        'export_excel'         => 'Xuất excel',
        'name'                 => 'Loại lý do',
        'fullname'             => 'Họ và tên',
        'sdate'                => 'Ngày bắt đầu',
        'edate'                => 'Ngày kết thúc',
        'start'                => 'Bắt đầu',
        'end'                  => 'Kết thúc',
        'time'                 => 'Thời gian (h)',
        'reason'               => 'Lý do',
        'remark'               => 'Ghi chú',
        'absentDate'           => 'Thời gian tạo',
        'approvedDate'         => 'Thời gian duyệt<br>(Người duyệt)',
        'approve'              => 'Trạng thái',
        'chooseRoom'           => 'Chọn phòng',
        'room'                 => 'Phòng',
    ],

    'interview' => [
        'add-job'             => 'Thêm công việc',
        'add-interview'       => 'Thêm lịch phỏng vấn',
        'interview-jobs'      => 'Danh sách công việc tuyển dụng',
        'interview-schedule'  => 'Quản lí lịch phỏng vấn',
        'list-candidate'      => 'Danh sách ứng viên',
        'add-candidate'       => 'Thêm ứng viên',
        'add-schedule'        => 'Thêm lịch phỏng vấn',
        'interview-schedules' => 'Lịch phỏng vấn đã hoàn thành',
        'recruitment-name'    => 'Tên công việc tuyển dụng',
        'add-recruitment'     => 'Thêm công việc tuyển dụng',
        'depiction'           => 'Mô tả ngắn',
        'address_now'         => 'Địa chỉ hiện tại',
        'name-job'            => 'Tên công việc',
        'name-inter'          => 'Tên ứng viên',
        'date'                => 'Ngày phỏng vấn',
        'Interviewer'         => 'Người phỏng vấn',
        'approved'            => 'Hoàn thành',
        'downloadCV'          => 'Tải CV',
        'Household'           => 'Hộ khẩu',
        'Current_residence'   => 'Nơi ở hiện tại',
        'Staying'             => 'Tạm trú',
        'detail'              => 'Chi tiết',
        'content_detail'      => 'Nội dung chi tiết',
    ],

    'calendar' => [
        'management'                    => 'Danh sách lịch',
        'name'                          => 'Tên lịch',
        'title'                         => 'Tiêu đề',
        'active'                        => 'Trạng thái',
        'add'                           => 'Thêm lịch',
        'ingredient'                    => 'Thành phần',
        'chair'                         => 'Chủ trì',
        'work-content'                  => 'Thêm lịch',
        'detailed-calendar-date'        => 'Chi tiết lịch ngày',
        'years'                         => 'Theo năm',
        'month'                         => 'Theo tháng',
        'week'                          => 'Theo tuần',
        'dayVietNam'                    => 'Ngày Việt - D/M/Y',
        'dayJapan'                      => 'Ngày Nhật - Y/M/D',
        'selectCalendar'                => 'Chọn lịch',
        'copyCalendar'                  => 'Sao chép lịch',
        'deleCalendar'                  => 'Xóa sự kiện',
        'work'                          => 'Nội dung công việc',
    ],

    'partner' => [
        'full_name'          => 'Họ và tên',
        'partner_management' => 'Danh sách đối tác',
        'add_new_partner'    => 'Thêm đối tác',
        'company'            => 'Công ty',
        'name_pr'            => 'Khách hàng',
        'sectors'            => 'Ngành hàng',
        'birthday'           => 'Ngày sinh',
        'tel'                => 'Số điện thoại',
        'email'              => 'Email',
        'address'            => 'Địa chỉ',
        'department_id'      => 'Chức vụ',
        'nameCompany'        => 'Tên công ty / Khách hàng',
        'InfoRepresentatives'=>'Thông tin người đại diện',
    ],

    'room_report' => [
        'room_report'     => 'Báo cáo phòng ban',
        'DateUpdate'      => 'Thời gian sửa',
        'Contents'        => 'Đề xuất',
        'unfinished_work' => 'Công việc tồn đọng',
        'week_work'       => 'Công việc tuần',
        'time'            => 'Thời gian',
        'noted'           => 'Ghi chú',
        'room'            => 'Phòng ban',
        'add_new'         => 'Thêm báo cáo phòng'
    ],

    'document' => [
        'dName'                 => 'Tên tài liệu',
        'dType'                 => 'Kiểu văn bản',
        'create_at'             => 'Ngày đăng tải',
        'byUser'                => 'Người đăng',
        'status_id'             => 'Trạng thái',
        'add-doc'               => 'Thêm tài liệu',
        'userView'              => 'Người xem',
        'tUpload'               => 'Kiểu upload',
        'url'                   => 'Đường dẫn',
        'upload'                => 'File',
        'select_doc'            => '[Chọn văn bản]',
        'select_file'           => 'Chọn file',
    ],

    'total_report' => [
        'screen_name' => 'Thống kê báo cáo',
    ],

    'role' => [
        'viewRole'              => 'Dánh sách quyền màn hình',
        'nameScreen'            => 'Tên màn hình',
        'isRole'                => 'Có quyền',
        'notRole'               => 'Không quyền',
        'function'              => 'Chức nămg',
    ]
];
